services:
  - type: web
    name: Irmandade-Conhecimento-com-Luz-1
    env: node
    plan: starter
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
